# Generated by Django 6.0.6 on 2026-07-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_ticket_ai_summary_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
