# Generated by Django 6.0.6 on 2026-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_service_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='private_incidents',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='allow_account_deletion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='allow_data_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='private_profile',
            field=models.BooleanField(default=False),
        ),
    ]
