# Generated by Django 6.0.6 on 2026-07-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_usersettings_private_incidents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
