# Generated by Django 6.0.6 on 2026-07-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_services_delete_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='services.incident'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='services.services'),
        ),
    ]
