# Generated by Django 6.0.6 on 2026-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_ticket_incident_ticket_service_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='affected_device',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Mobile Phone', 'Mobile Phone'), ('Tablet', 'Tablet'), ('Server', 'Server'), ('Network', 'Network'), ('Website', 'Website'), ('Email', 'Email'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='assistance_type',
            field=models.CharField(choices=[('Prevention', 'Prevention'), ('Inspection', 'Inspection'), ('Incident Response', 'Incident Response')], default='Inspection', max_length=30),
        ),
        migrations.AddField(
            model_name='services',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/'),
        ),
        migrations.AddField(
            model_name='services',
            name='client_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Company', 'Company')], default='Personal', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='incident_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
