# Generated by Django 6.0.6 on 2026-07-04 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_services_affected_device_services_assistance_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityreport',
            name='user',
        ),
        migrations.AddField(
            model_name='securityreport',
            name='analyst',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_reports',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='service',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reports',
                to='services.services',
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='incident_days',
            field=models.PositiveIntegerField(),
        ),
    ]
