# Generated by Django 6.0.6 on 2026-07-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_services_affected_device_services_assistance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='affected_device',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Mobile Phone', 'Mobile Phone'), ('Tablet', 'Tablet'), ('Server', 'Server'), ('Network', 'Network'), ('Website', 'Website'), ('Email', 'Email'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='assistance_type',
            field=models.CharField(choices=[('Prevention', 'Prevention'), ('Inspection', 'Inspection'), ('Incident Response', 'Incident Response')], default='Inspection', max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
