# Generated by Django 6.0.6 on 2026-07-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_services_affected_device_and_more'),
        ('services', '0011_remove_securityreport_user_securityreport_analyst_and_more'),
    ]

    operations = [
    ]
