# Generated by Django 6.0.6 on 2026-07-06 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_merge_20260704_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='services',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='services',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('M-Pesa', 'M-Pesa'), ('Card', 'Credit/Debit Card'), ('Bank', 'Bank Transfer')], max_length=30),
        ),
        migrations.AddField(
            model_name='services',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='services',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.services'),
            preserve_default=False,
        ),
    ]
