# Generated by Django 6.0.6 on 2026-07-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestigationReport',
        ),
    ]
