# Generated by Django 6.0.6 on 2026-07-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_delete_investigationreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
