# Generated by Django 6.0.6 on 2026-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('PROFESSIONAL', 'Professional'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
